"""init: model_configs, document_templates, laws, error_patterns, generation_history

Revision ID: 103645220e8f
Revises: 
Create Date: 2026-05-26 18:25:33.298349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '103645220e8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('schema_fields', sqlite.JSON(), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_templates_doc_type'), 'document_templates', ['doc_type'], unique=True)
    op.create_table('error_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('error_description', sa.Text(), nullable=False),
    sa.Column('incorrect_example', sa.Text(), nullable=False),
    sa.Column('correct_example', sa.Text(), nullable=False),
    sa.Column('applicable_doc_types', sqlite.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('output_content', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=128), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('elements', sqlite.JSON(), nullable=False),
    sa.Column('suggested_laws', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_history_created_at'), 'generation_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_generation_history_doc_type'), 'generation_history', ['doc_type'], unique=False)
    op.create_table('laws',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('law_name', sa.String(length=256), nullable=False),
    sa.Column('article_number', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('penalty_range', sa.String(length=256), nullable=False),
    sa.Column('keywords', sqlite.JSON(), nullable=False),
    sa.Column('applicable_doc_types', sqlite.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laws_law_name'), 'laws', ['law_name'], unique=False)
    op.create_table('model_configs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_name_large', sa.String(length=128), nullable=False),
    sa.Column('api_key', sa.String(length=512), nullable=False),
    sa.Column('api_type', sa.String(length=32), nullable=False),
    sa.Column('requires_key', sa.Boolean(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_configs')
    op.drop_index(op.f('ix_laws_law_name'), table_name='laws')
    op.drop_table('laws')
    op.drop_index(op.f('ix_generation_history_doc_type'), table_name='generation_history')
    op.drop_index(op.f('ix_generation_history_created_at'), table_name='generation_history')
    op.drop_table('generation_history')
    op.drop_table('error_patterns')
    op.drop_index(op.f('ix_document_templates_doc_type'), table_name='document_templates')
    op.drop_table('document_templates')
    # ### end Alembic commands ###
